{
 "title": "Felipe Antônio Lohn",
 "tags": [
  "zabbix",
  "mysql"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Instância",
    "query": "label_values(up{job=\"telegraf\"},instance)"
   },
   { "name": "group", "query": "Felipe Lohn" },
   { "name": "nobreak", "query": "$group.*" },
   { "name": "freepbx", "query": "$group.*" },
   { "name": "exacqvision", "query": "$group.*" },
   { "name": "accessus", "query": "$group.*" },
   { "name": "interfones", "query": "$group.*" },
   { "name": "groupid", "query": "32" },
   { "name": "controllers", "query": "$group.*" },
   { "name": "cftv", "query": "$group.*" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "content": "<h1 style=\"text-align: center; background-color: #8700db; margin: 0px; border: 0px; height:100%;\"><p style=\"position: absolute; padding-top: 1.5%;\">ENERGIA</p></h1>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "content": "<h1 style=\"text-align: center; background-color: red; margin: 0px; border: 0px; height:100%;\"><p style=\"position: absolute; padding-top: 1.5%;\">INCIDENTES</p></h1>"
  },
  {
   "title": "% Carga da bateria - Nobreak",
   "type": "singlestat",
   "description": "% Carga da bateria - Nobreak",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "UPS Battery" },
     "group": { "filter": "$group" },
     "host": { "filter": "$nobreak" },
     "item": { "filter": "Battery Capacity [HighPrec]" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "status de troca da batéria - Nobreak",
   "type": "singlestat",
   "description": "status de troca da batéria - Nobreak",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "UPS Battery" },
     "group": { "filter": "$group" },
     "host": { "filter": "$nobreak" },
     "item": { "filter": "Battery Status" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tempo de autonomia",
   "type": "singlestat",
   "description": "Tempo de autonomia",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 2 },
   "format": "dthms",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$nobreak" },
     "item": { "filter": "Battery Runtime" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cº Temperatura Telecom",
   "type": "singlestat",
   "description": "Cº Temperatura da telecom",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "UPS Information" },
     "group": { "filter": "$group" },
     "host": { "filter": "$nobreak" },
     "item": { "filter": "Probe Temperature" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Log de alertas ",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "description": "Log de alertas ",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 5 },
   "content": "<h1 style=\"text-align: center; background-color: darkblue; margin: 0px; border: 0px; height:100%;\"><p style=\"position: absolute; padding-top: 1.5%;\">CONTROLE DE ACESSO</p></h1>"
  },
  {
   "title": "Disponibilidade Accessus",
   "type": "singlestat",
   "description": "Disponibilidade do controle de accessus",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Status" },
     "group": { "filter": "$group" },
     "host": { "filter": "$accessus" },
     "item": { "filter": "Zabbix agent availability" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Controladoras Up",
   "type": "singlestat",
   "description": "Controladoras Down",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \ncount(distinct hosts.name) as \"Up\"\nfrom history_uint \n    inner join items on\n    items.itemid = history_uint.itemid\n    inner join hosts on\n    items.hostid = hosts.hostid\n    inner join hosts_groups on\n    hosts.hostid = hosts_groups.hostid\nwhere \n  hosts_groups.groupid = $groupid and\n  hosts.name in($controllers) and\n  history_uint.clock between (UNIX_TIMESTAMP() - 700) and UNIX_TIMESTAMP() and\n  history_uint.value = 1\n"
    }
   ]
  },
  {
   "title": "Controladoras Down",
   "type": "singlestat",
   "description": "Quantidade de controladoras down",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \ncount(distinct hosts.name) as \"Down\"\nfrom history_uint \n    inner join items on\n    items.itemid = history_uint.itemid\n    inner join hosts on\n    items.hostid = hosts.hostid\n    inner join hosts_groups on\n    hosts.hostid = hosts_groups.hostid\nwhere \n  hosts_groups.groupid = $groupid and\n  hosts.name in($controllers) and\n  history_uint.clock between (UNIX_TIMESTAMP() - 700) and UNIX_TIMESTAMP() and\n  history_uint.value = 0"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 10 },
   "content": "<h1 style=\"text-align: center; background-color: #3366ff; margin: 0px; border: 0px; height:100%;\"><p style=\"position: absolute; padding-top: 1.5%;\">VIDEO MONITORAMENTO</p></h1>"
  },
  {
   "title": "Disponibilidade ExacqVision",
   "type": "singlestat",
   "description": "Disponibilidade ExacqVision",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Status" },
     "group": { "filter": "$group" },
     "host": { "filter": "$exacqvision" },
     "item": { "filter": "Zabbix agent availability" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Armazenamento Exaqvision",
   "type": "singlestat",
   "description": "Armazenamento Exaqvision",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n(((SELECT \n    avg(history_uint.value)\n    from history_uint \n         inner join items on\n         items.itemid = history_uint.itemid\n         inner join hosts on\n         items.hostid = hosts.hostid\n         inner join hosts_groups on\n        hosts.hostid = hosts_groups.hostid\n    where \n      hosts_groups.groupid = $groupid and\n      hosts.name in(\"$exacqvision\") and\n      history_uint.clock between (UNIX_TIMESTAMP() - 700) and UNIX_TIMESTAMP() and \n      items.name in(\"/mnt/edvr/1: Used space\") limit 1\n     ) / \n\n(SELECT \n    avg(history_uint.value)\n    from history_uint \n         inner join items on\n         items.itemid = history_uint.itemid\n         inner join hosts on\n         items.hostid = hosts.hostid\n         inner join hosts_groups on\n        hosts.hostid = hosts_groups.hostid\n    where \n      hosts_groups.groupid = $groupid and\n      hosts.name in(\"$exacqvision\") and\n      history_uint.clock between (UNIX_TIMESTAMP() - 700) and UNIX_TIMESTAMP() and \n      items.name in(\"/mnt/edvr/1: Total space\") limit 1\n     )) * 100) as \"Percentual de consumo\"\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Câmeras Up",
   "type": "singlestat",
   "description": "Câmeras em funcionamento",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \ncount(distinct hosts.name) as \"Up\"\nfrom history_uint \n    inner join items on\n    items.itemid = history_uint.itemid\n    inner join hosts on\n    items.hostid = hosts.hostid\n    inner join hosts_groups on\n    hosts.hostid = hosts_groups.hostid\nwhere \n  hosts_groups.groupid = $groupid and\n  hosts.name in($cftv) and\n  history_uint.clock between (UNIX_TIMESTAMP() - 700) and UNIX_TIMESTAMP() and\n  history_uint.value = 1\n"
    }
   ]
  },
  {
   "title": "Câmeras  Down",
   "type": "singlestat",
   "description": "Quantidade de câmeras sem funcionamento",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \ncount(distinct hosts.name) as \"Down\"\nfrom history_uint \n    inner join items on\n    items.itemid = history_uint.itemid\n    inner join hosts on\n    items.hostid = hosts.hostid\n    inner join hosts_groups on\n    hosts.hostid = hosts_groups.hostid\nwhere \n  hosts_groups.groupid = $groupid and\n  hosts.name in($cftv) and\n  history_uint.clock between (UNIX_TIMESTAMP() - 700) and UNIX_TIMESTAMP() and\n  history_uint.value = 0"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 15 },
   "content": "<h1 style=\"text-align: center; background-color: #0e5709; margin: 0px; border: 0px; height:100%;\"><p style=\"position: absolute; padding-top: 1.5%;\">TELEFONIA</p></h1>"
  },
  {
   "title": "Disponibilidade FreePBX",
   "type": "singlestat",
   "description": "Disponibilidade FreePBX",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Status" },
     "group": { "filter": "$group" },
     "host": { "filter": "$freepbx" },
     "item": { "filter": "Zabbix agent availability" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Interfones Up",
   "type": "singlestat",
   "description": "Quantidade de Interfones Up",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \ncount(distinct hosts.name) as \"Up\"\nfrom history_uint \n    inner join items on\n    items.itemid = history_uint.itemid\n    inner join hosts on\n    items.hostid = hosts.hostid\n    inner join hosts_groups on\n    hosts.hostid = hosts_groups.hostid\nwhere \n  hosts_groups.groupid = $groupid and\n  hosts.name in($interfones) and\n  history_uint.clock between (UNIX_TIMESTAMP() - 700) and UNIX_TIMESTAMP() and\n  history_uint.value = 1\n"
    }
   ]
  },
  {
   "title": "Interfones Down",
   "type": "singlestat",
   "description": "Quantidade de interfones down",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \ncount(distinct hosts.name) as \"Down\"\nfrom history_uint \n    inner join items on\n    items.itemid = history_uint.itemid\n    inner join hosts on\n    items.hostid = hosts.hostid\n    inner join hosts_groups on\n    hosts.hostid = hosts_groups.hostid\nwhere \n  hosts_groups.groupid = $groupid and\n  hosts.name in($interfones) and\n  history_uint.clock between (UNIX_TIMESTAMP() - 700) and UNIX_TIMESTAMP() and\n  history_uint.value = 0"
    }
   ]
  }
 ]
}